"""add table users

Revision ID: 9f815149367c
Revises: 
Create Date: 2025-12-14 01:12:15.875818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f815149367c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.create_table(
        'users',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('username', sa.String(50), nullable=False),
        sa.Column('file', sa.String(200)),
        sa.Column('date_reg', sa.String(), nullable=False),
        sa.Column('date_born', sa.String(), nullable=False),
        sa.Column('age', sa.Integer, nullable=False),
        sa.Column('password', sa.String(), nullable=False),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
